const skills = [
  { id: 0, name: 'No Skill' },
  { id: 1, name: 'Healing Signet' },
  { id: 2, name: 'Resurrection Signet' },
  { id: 3, name: 'Signet of Capture' },
  { id: 5, name: 'Power Block' },
  { id: 6, name: 'Mantra of Earth' },
  { id: 7, name: 'Mantra of Flame' },
  { id: 8, name: 'Mantra of Frost' },
  { id: 9, name: 'Mantra of Lightning' },
  { id: 10, name: 'Hex Breaker' },
  { id: 11, name: 'Distortion' },
  { id: 13, name: 'Mantra of Recovery' },
  { id: 14, name: 'Mantra of Persistence' },
  { id: 15, name: 'Mantra of Inscriptions' },
  { id: 16, name: 'Mantra of Concentration' },
  { id: 17, name: 'Mantra of Resolve' },
  { id: 18, name: 'Mantra of Signets' },
  { id: 19, name: 'Fragility' },
  { id: 21, name: 'Inspired Enchantment' },
  { id: 22, name: 'Inspired Hex' },
  { id: 23, name: 'Power Spike' },
  { id: 24, name: 'Power Leak' },
  { id: 25, name: 'Power Drain' },
  { id: 26, name: 'Empathy' },
  { id: 27, name: 'Shatter Delusions' },
  { id: 28, name: 'Backfire' },
  { id: 29, name: 'Blackout' },
  { id: 30, name: 'Diversion' },
  { id: 31, name: 'Conjure Phantasm' },
  { id: 32, name: 'Illusion of Weakness' },
  { id: 33, name: 'Illusionary Weaponry' },
  { id: 34, name: 'Sympathetic Visage' },
  { id: 35, name: 'Ignorance' },
  { id: 36, name: 'Arcane Conundrum' },
  { id: 37, name: 'Illusion of Haste' },
  { id: 38, name: 'Channeling' },
  { id: 39, name: 'Energy Surge' },
  { id: 40, name: 'Ether Feast' },
  { id: 41, name: 'Ether Lord' },
  { id: 42, name: 'Energy Burn' },
  { id: 43, name: 'Clumsiness' },
  { id: 44, name: 'Phantom Pain' },
  { id: 45, name: 'Ethereal Burden' },
  { id: 46, name: 'Guilt' },
  { id: 47, name: 'Ineptitude' },
  { id: 48, name: 'Spirit of Failure' },
  { id: 49, name: 'Mind Wrack' },
  { id: 50, name: "Wastrel's Worry" },
  { id: 51, name: 'Shame' },
  { id: 52, name: 'Panic' },
  { id: 53, name: 'Migraine' },
  { id: 54, name: 'Crippling Anguish' },
  { id: 55, name: 'Fevered Dreams' },
  { id: 56, name: 'Soothing Images' },
  { id: 57, name: 'Cry of Frustration' },
  { id: 58, name: 'Signet of Midnight' },
  { id: 59, name: 'Signet of Weariness' },
  { id: 61, name: 'Leech Signet' },
  { id: 62, name: 'Signet of Humility' },
  { id: 63, name: 'Keystone Signet' },
  { id: 65, name: 'Arcane Mimicry' },
  { id: 66, name: 'Spirit Shackles' },
  { id: 67, name: 'Shatter Hex' },
  { id: 68, name: 'Drain Enchantment' },
  { id: 69, name: 'Shatter Enchantment' },
  { id: 72, name: 'Elemental Resistance' },
  { id: 73, name: 'Physical Resistance' },
  { id: 74, name: 'Echo' },
  { id: 75, name: 'Arcane Echo' },
  { id: 76, name: 'Imagined Burden' },
  { id: 77, name: 'Chaos Storm' },
  { id: 78, name: 'Epidemic' },
  { id: 79, name: 'Energy Drain' },
  { id: 80, name: 'Energy Tap' },
  { id: 81, name: 'Arcane Thievery' },
  { id: 82, name: 'Mantra of Recall' },
  { id: 83, name: 'Animate Bone Horror' },
  { id: 84, name: 'Animate Bone Fiend' },
  { id: 85, name: 'Animate Bone Minions' },
  { id: 86, name: "Grenth's Balance" },
  { id: 87, name: "Verata's Gaze" },
  { id: 88, name: "Verata's Aura" },
  { id: 89, name: 'Deathly Chill' },
  { id: 90, name: "Verata's Sacrifice" },
  { id: 91, name: 'Well of Power' },
  { id: 92, name: 'Well of Blood' },
  { id: 93, name: 'Well of Suffering' },
  { id: 94, name: 'Well of the Profane' },
  { id: 95, name: 'Putrid Explosion' },
  { id: 96, name: 'Soul Feast' },
  { id: 97, name: 'Necrotic Traversal' },
  { id: 98, name: 'Consume Corpse' },
  { id: 99, name: 'Parasitic Bond' },
  { id: 100, name: 'Soul Barbs' },
  { id: 101, name: 'Barbs' },
  { id: 102, name: 'Shadow Strike' },
  { id: 103, name: 'Price of Failure' },
  { id: 104, name: 'Death Nova' },
  { id: 105, name: 'Deathly Swarm' },
  { id: 106, name: 'Rotting Flesh' },
  { id: 107, name: 'Virulence' },
  { id: 108, name: 'Suffering' },
  { id: 109, name: 'Life Siphon' },
  { id: 110, name: 'Unholy Feast' },
  { id: 111, name: 'Awaken the Blood' },
  { id: 112, name: 'Desecrate Enchantments' },
  { id: 113, name: 'Tainted Flesh' },
  { id: 114, name: 'Aura of the Lich' },
  { id: 115, name: 'Blood Renewal' },
  { id: 116, name: 'Dark Aura' },
  { id: 117, name: 'Enfeeble' },
  { id: 118, name: 'Enfeebling Blood' },
  { id: 119, name: 'Blood is Power' },
  { id: 120, name: 'Blood of the Master' },
  { id: 121, name: 'Spiteful Spirit' },
  { id: 122, name: 'Malign Intervention' },
  { id: 123, name: 'Insidious Parasite' },
  { id: 124, name: 'Spinal Shivers' },
  { id: 125, name: 'Wither' },
  { id: 126, name: 'Life Transfer' },
  { id: 127, name: 'Mark of Subversion' },
  { id: 128, name: 'Soul Leech' },
  { id: 129, name: 'Defile Flesh' },
  { id: 130, name: 'Demonic Flesh' },
  { id: 131, name: 'Barbed Signet' },
  { id: 132, name: 'Plague Signet' },
  { id: 133, name: 'Dark Pact' },
  { id: 134, name: 'Order of Pain' },
  { id: 135, name: 'Faintheartedness' },
  { id: 136, name: 'Shadow of Fear' },
  { id: 137, name: 'Rigor Mortis' },
  { id: 138, name: 'Dark Bond' },
  { id: 139, name: 'Infuse Condition' },
  { id: 140, name: 'Malaise' },
  { id: 141, name: 'Rend Enchantments' },
  { id: 142, name: 'Lingering Curse' },
  { id: 143, name: 'Strip Enchantment' },
  { id: 144, name: 'Chilblains' },
  { id: 145, name: 'Signet of Agony' },
  { id: 146, name: 'Offering of Blood' },
  { id: 147, name: 'Dark Fury' },
  { id: 148, name: 'Order of the Vampire' },
  { id: 149, name: 'Plague Sending' },
  { id: 150, name: 'Mark of Pain' },
  { id: 151, name: 'Feast of Corruption' },
  { id: 152, name: 'Taste of Death' },
  { id: 153, name: 'Vampiric Gaze' },
  { id: 154, name: 'Plague Touch' },
  { id: 155, name: 'Vile Touch' },
  { id: 156, name: 'Vampiric Touch' },
  { id: 157, name: 'Blood Ritual' },
  { id: 158, name: 'Touch of Agony' },
  { id: 159, name: 'Weaken Armor' },
  { id: 160, name: 'Windborne Speed' },
  { id: 162, name: 'Gale' },
  { id: 163, name: 'Whirlwind' },
  { id: 164, name: 'Elemental Attunement' },
  { id: 165, name: 'Armor of Earth' },
  { id: 166, name: 'Kinetic Armor' },
  { id: 167, name: 'Eruption' },
  { id: 168, name: 'Magnetic Aura' },
  { id: 169, name: 'Earth Attunement' },
  { id: 170, name: 'Earthquake' },
  { id: 171, name: 'Stoning' },
  { id: 172, name: 'Stone Daggers' },
  { id: 173, name: 'Grasping Earth' },
  { id: 174, name: 'Aftershock' },
  { id: 175, name: 'Ward Against Elements' },
  { id: 176, name: 'Ward Against Melee' },
  { id: 177, name: 'Ward Against Foes' },
  { id: 178, name: 'Ether Prodigy' },
  { id: 179, name: 'Incendiary Bonds' },
  { id: 180, name: 'Aura of Restoration' },
  { id: 181, name: 'Ether Renewal' },
  { id: 182, name: 'Conjure Flame' },
  { id: 183, name: 'Inferno' },
  { id: 184, name: 'Fire Attunement' },
  { id: 185, name: 'Mind Burn' },
  { id: 186, name: 'Fireball' },
  { id: 187, name: 'Meteor' },
  { id: 188, name: 'Flame Burst' },
  { id: 189, name: "Rodgort's Invocation" },
  { id: 190, name: 'Mark of Rodgort' },
  { id: 191, name: 'Immolate' },
  { id: 192, name: 'Meteor Shower' },
  { id: 193, name: 'Phoenix' },
  { id: 194, name: 'Flare' },
  { id: 195, name: 'Lava Font' },
  { id: 196, name: 'Searing Heat' },
  { id: 197, name: 'Fire Storm' },
  { id: 198, name: 'Glyph of Elemental Power' },
  { id: 199, name: 'Glyph of Energy' },
  { id: 200, name: 'Glyph of Lesser Energy' },
  { id: 201, name: 'Glyph of Concentration' },
  { id: 202, name: 'Glyph of Sacrifice' },
  { id: 203, name: 'Glyph of Renewal' },
  { id: 204, name: 'Rust' },
  { id: 205, name: 'Lightning Surge' },
  { id: 206, name: 'Armor of Frost' },
  { id: 207, name: 'Conjure Frost' },
  { id: 208, name: 'Water Attunement' },
  { id: 209, name: 'Mind Freeze' },
  { id: 210, name: 'Ice Prison' },
  { id: 211, name: 'Ice Spikes' },
  { id: 212, name: 'Frozen Burst' },
  { id: 213, name: 'Shard Storm' },
  { id: 214, name: 'Ice Spear' },
  { id: 215, name: 'Maelstrom' },
  { id: 216, name: 'Iron Mist' },
  { id: 217, name: 'Crystal Wave' },
  { id: 218, name: 'Obsidian Flesh' },
  { id: 219, name: 'Obsidian Flame' },
  { id: 220, name: 'Blinding Flash' },
  { id: 221, name: 'Conjure Lightning' },
  { id: 222, name: 'Lightning Strike' },
  { id: 223, name: 'Chain Lightning' },
  { id: 224, name: 'Enervating Charge' },
  { id: 225, name: 'Air Attunement' },
  { id: 226, name: 'Mind Shock' },
  { id: 227, name: 'Glimmering Mark' },
  { id: 228, name: 'Thunderclap' },
  { id: 229, name: 'Lightning Orb' },
  { id: 230, name: 'Lightning Javelin' },
  { id: 231, name: 'Shock' },
  { id: 232, name: 'Lightning Touch' },
  { id: 233, name: 'Swirling Aura' },
  { id: 234, name: 'Deep Freeze' },
  { id: 235, name: 'Blurred Vision' },
  { id: 236, name: 'Mist Form' },
  { id: 237, name: 'Water Trident' },
  { id: 238, name: 'Armor of Mist' },
  { id: 239, name: 'Ward Against Harm' },
  { id: 240, name: 'Smite' },
  { id: 241, name: 'Life Bond' },
  { id: 242, name: "Balthazar's Spirit" },
  { id: 243, name: 'Strength of Honor' },
  { id: 244, name: 'Life Attunement' },
  { id: 245, name: 'Protective Spirit' },
  { id: 246, name: 'Divine Intervention' },
  { id: 247, name: 'Symbol of Wrath' },
  { id: 248, name: 'Retribution' },
  { id: 249, name: 'Holy Wrath' },
  { id: 250, name: 'Essence Bond' },
  { id: 251, name: 'Scourge Healing' },
  { id: 252, name: 'Banish' },
  { id: 253, name: 'Scourge Sacrifice' },
  { id: 254, name: 'Vigorous Spirit' },
  { id: 255, name: 'Watchful Spirit' },
  { id: 256, name: 'Blessed Aura' },
  { id: 257, name: 'Aegis' },
  { id: 258, name: 'Guardian' },
  { id: 259, name: 'Shield of Deflection' },
  { id: 260, name: 'Aura of Faith' },
  { id: 261, name: 'Shield of Regeneration' },
  { id: 262, name: 'Shield of Judgment' },
  { id: 263, name: 'Protective Bond' },
  { id: 264, name: 'Pacifism' },
  { id: 265, name: 'Amity' },
  { id: 266, name: 'Peace and Harmony' },
  { id: 267, name: "Judge's Insight" },
  { id: 268, name: 'Unyielding Aura' },
  { id: 269, name: 'Mark of Protection' },
  { id: 270, name: 'Life Barrier' },
  { id: 271, name: "Zealot's Fire" },
  { id: 272, name: "Balthazar's Aura" },
  { id: 273, name: 'Spell Breaker' },
  { id: 274, name: 'Healing Seed' },
  { id: 275, name: 'Mend Condition' },
  { id: 276, name: 'Restore Condition' },
  { id: 277, name: 'Mend Ailment' },
  { id: 278, name: 'Purge Conditions' },
  { id: 279, name: 'Divine Healing' },
  { id: 280, name: 'Heal Area' },
  { id: 281, name: 'Orison of Healing' },
  { id: 282, name: 'Word of Healing' },
  { id: 283, name: "Dwayna's Kiss" },
  { id: 284, name: 'Divine Boon' },
  { id: 285, name: 'Healing Hands' },
  { id: 286, name: 'Heal Other' },
  { id: 287, name: 'Heal Party' },
  { id: 288, name: 'Healing Breeze' },
  { id: 289, name: 'Vital Blessing' },
  { id: 290, name: 'Mending' },
  { id: 291, name: 'Live Vicariously' },
  { id: 292, name: 'Infuse Health' },
  { id: 293, name: 'Signet of Devotion' },
  { id: 294, name: 'Signet of Judgment' },
  { id: 295, name: 'Purge Signet' },
  { id: 296, name: 'Bane Signet' },
  { id: 297, name: 'Blessed Signet' },
  { id: 298, name: 'Martyr' },
  { id: 299, name: 'Shielding Hands' },
  { id: 300, name: 'Contemplation of Purity' },
  { id: 301, name: 'Remove Hex' },
  { id: 302, name: 'Smite Hex' },
  { id: 303, name: 'Convert Hexes' },
  { id: 304, name: 'Light of Dwayna' },
  { id: 305, name: 'Resurrect' },
  { id: 306, name: 'Rebirth' },
  { id: 307, name: 'Reversal of Fortune' },
  { id: 308, name: 'Succor' },
  { id: 309, name: 'Holy Veil' },
  { id: 310, name: 'Divine Spirit' },
  { id: 311, name: 'Draw Conditions' },
  { id: 312, name: 'Holy Strike' },
  { id: 313, name: 'Healing Touch' },
  { id: 314, name: 'Restore Life' },
  { id: 315, name: 'Vengeance' },
  { id: 316, name: '&quot;To the Limit!&quot;' },
  { id: 317, name: 'Battle Rage' },
  { id: 318, name: 'Defy Pain' },
  { id: 319, name: 'Rush' },
  { id: 320, name: 'Hamstring' },
  { id: 321, name: 'Wild Blow' },
  { id: 322, name: 'Power Attack' },
  { id: 323, name: 'Desperation Blow' },
  { id: 324, name: 'Thrill of Victory' },
  { id: 325, name: 'Distracting Blow' },
  { id: 326, name: "Protector's Strike" },
  { id: 327, name: "Griffon's Sweep" },
  { id: 328, name: 'Pure Strike' },
  { id: 329, name: 'Skull Crack' },
  { id: 330, name: 'Cyclone Axe' },
  { id: 331, name: 'Hammer Bash' },
  { id: 332, name: "Bull's Strike" },
  { id: 333, name: '&quot;I Will Avenge You!&quot;' },
  { id: 334, name: 'Axe Rake' },
  { id: 335, name: 'Cleave' },
  { id: 336, name: "Executioner's Strike" },
  { id: 337, name: 'Dismember' },
  { id: 338, name: 'Eviscerate' },
  { id: 339, name: 'Penetrating Blow' },
  { id: 340, name: 'Disrupting Chop' },
  { id: 341, name: 'Swift Chop' },
  { id: 342, name: 'Axe Twist' },
  { id: 343, name: '&quot;For Great Justice!&quot;' },
  { id: 344, name: 'Flurry' },
  { id: 345, name: 'Defensive Stance' },
  { id: 346, name: 'Frenzy' },
  { id: 347, name: 'Endure Pain' },
  { id: 348, name: '&quot;Watch Yourself!&quot;' },
  { id: 349, name: 'Sprint' },
  { id: 350, name: 'Belly Smash' },
  { id: 351, name: 'Mighty Blow' },
  { id: 352, name: 'Crushing Blow' },
  { id: 353, name: 'Crude Swing' },
  { id: 354, name: 'Earth Shaker' },
  { id: 355, name: 'Devastating Hammer' },
  { id: 356, name: 'Irresistible Blow' },
  { id: 357, name: 'Counter Blow' },
  { id: 358, name: 'Backbreaker' },
  { id: 359, name: 'Heavy Blow' },
  { id: 360, name: 'Staggering Blow' },
  { id: 361, name: 'Dolyak Signet' },
  { id: 362, name: "Warrior's Cunning" },
  { id: 363, name: 'Shield Bash' },
  { id: 364, name: '&quot;Charge!&quot;' },
  { id: 365, name: '&quot;Victory Is Mine!&quot;' },
  { id: 366, name: '&quot;Fear Me!&quot;' },
  { id: 367, name: '&quot;Shields Up!&quot;' },
  { id: 368, name: '&quot;I Will Survive!&quot;' },
  { id: 370, name: 'Berserker Stance' },
  { id: 371, name: 'Balanced Stance' },
  { id: 372, name: "Gladiator's Defense" },
  { id: 373, name: 'Deflect Arrows' },
  { id: 374, name: "Warrior's Endurance" },
  { id: 375, name: 'Dwarven Battle Stance' },
  { id: 376, name: 'Disciplined Stance' },
  { id: 377, name: 'Wary Stance' },
  { id: 378, name: 'Shield Stance' },
  { id: 379, name: "Bull's Charge" },
  { id: 380, name: "Bonetti's Defense" },
  { id: 381, name: 'Hundred Blades' },
  { id: 382, name: 'Sever Artery' },
  { id: 383, name: 'Galrath Slash' },
  { id: 384, name: 'Gash' },
  { id: 385, name: 'Final Thrust' },
  { id: 386, name: 'Seeking Blade' },
  { id: 387, name: 'Riposte' },
  { id: 388, name: 'Deadly Riposte' },
  { id: 389, name: 'Flourish' },
  { id: 390, name: 'Savage Slash' },
  { id: 391, name: "Hunter's Shot" },
  { id: 392, name: 'Pin Down' },
  { id: 393, name: 'Crippling Shot' },
  { id: 394, name: 'Power Shot' },
  { id: 395, name: 'Barrage' },
  { id: 396, name: 'Dual Shot' },
  { id: 397, name: 'Quick Shot' },
  { id: 398, name: 'Penetrating Attack' },
  { id: 399, name: 'Distracting Shot' },
  { id: 400, name: 'Precision Shot' },
  { id: 402, name: 'Determined Shot' },
  { id: 403, name: 'Called Shot' },
  { id: 404, name: 'Poison Arrow' },
  { id: 405, name: 'Oath Shot' },
  { id: 406, name: 'Debilitating Shot' },
  { id: 407, name: 'Point Blank Shot' },
  { id: 408, name: 'Concussion Shot' },
  { id: 409, name: 'Punishing Shot' },
  { id: 411, name: 'Charm Animal' },
  { id: 412, name: 'Call of Protection' },
  { id: 415, name: 'Call of Haste' },
  { id: 422, name: 'Revive Animal' },
  { id: 423, name: 'Symbiotic Bond' },
  { id: 424, name: 'Throw Dirt' },
  { id: 425, name: 'Dodge' },
  { id: 426, name: 'Savage Shot' },
  { id: 427, name: 'Antidote Signet' },
  { id: 428, name: 'Incendiary Arrows' },
  { id: 429, name: "Melandru's Arrows" },
  { id: 430, name: "Marksman's Wager" },
  { id: 431, name: 'Ignite Arrows' },
  { id: 432, name: 'Read the Wind' },
  { id: 433, name: 'Kindle Arrows' },
  { id: 434, name: 'Choking Gas' },
  { id: 435, name: 'Apply Poison' },
  { id: 436, name: 'Comfort Animal' },
  { id: 437, name: 'Bestial Pounce' },
  { id: 438, name: 'Maiming Strike' },
  { id: 439, name: 'Feral Lunge' },
  { id: 440, name: 'Scavenger Strike' },
  { id: 441, name: "Melandru's Assault" },
  { id: 442, name: 'Ferocious Strike' },
  { id: 443, name: "Predator's Pounce" },
  { id: 444, name: 'Brutal Strike' },
  { id: 445, name: 'Disrupting Lunge' },
  { id: 446, name: 'Troll Unguent' },
  { id: 447, name: "Otyugh's Cry" },
  { id: 448, name: 'Escape' },
  { id: 449, name: 'Practiced Stance' },
  { id: 450, name: 'Whirling Defense' },
  { id: 451, name: "Melandru's Resilience" },
  { id: 452, name: "Dryder's Defenses" },
  { id: 453, name: 'Lightning Reflexes' },
  { id: 454, name: "Tiger's Fury" },
  { id: 455, name: 'Storm Chaser' },
  { id: 456, name: "Serpent's Quickness" },
  { id: 457, name: 'Dust Trap' },
  { id: 458, name: 'Barbed Trap' },
  { id: 459, name: 'Flame Trap' },
  { id: 460, name: 'Healing Spring' },
  { id: 461, name: 'Spike Trap' },
  { id: 462, name: 'Winter' },
  { id: 463, name: 'Winnowing' },
  { id: 464, name: 'Edge of Extinction' },
  { id: 465, name: 'Greater Conflagration' },
  { id: 466, name: 'Conflagration' },
  { id: 467, name: 'Fertile Season' },
  { id: 468, name: 'Symbiosis' },
  { id: 469, name: 'Primal Echoes' },
  { id: 470, name: 'Predatory Season' },
  { id: 471, name: 'Frozen Soil' },
  { id: 472, name: 'Favorable Winds' },
  { id: 474, name: 'Energizing Wind' },
  { id: 475, name: 'Quickening Zephyr' },
  { id: 476, name: "Nature's Renewal" },
  { id: 477, name: 'Muddy Terrain' },
  { id: 570, name: 'Mark of Insecurity' },
  { id: 571, name: 'Disrupting Dagger' },
  { id: 572, name: 'Deadly Paradox' },
  { id: 763, name: 'Jaundiced Gaze' },
  { id: 764, name: 'Wail of Doom' },
  { id: 766, name: 'Gaze of Contempt' },
  { id: 769, name: "Viper's Defense" },
  { id: 770, name: 'Return' },
  { id: 771, name: 'Aura of Displacement' },
  { id: 772, name: 'Generous Was Tsungrai' },
  { id: 773, name: 'Mighty Was Vorizun' },
  { id: 775, name: 'Death Blossom' },
  { id: 776, name: 'Twisting Fangs' },
  { id: 777, name: 'Horns of the Ox' },
  { id: 778, name: 'Falling Spider' },
  { id: 779, name: 'Black Lotus Strike' },
  { id: 780, name: 'Fox Fangs' },
  { id: 781, name: 'Moebius Strike' },
  { id: 782, name: 'Jagged Strike' },
  { id: 783, name: 'Unsuspecting Strike' },
  { id: 784, name: 'Entangling Asp' },
  { id: 785, name: 'Mark of Death' },
  { id: 786, name: 'Iron Palm' },
  { id: 787, name: 'Resilient Weapon' },
  { id: 788, name: 'Blind Was Mingson' },
  { id: 789, name: 'Grasping Was Kuurong' },
  { id: 790, name: 'Vengeful Was Khanhei' },
  { id: 791, name: 'Flesh of My Flesh' },
  { id: 792, name: 'Splinter Weapon' },
  { id: 793, name: 'Weapon of Warding' },
  { id: 794, name: 'Wailing Weapon' },
  { id: 795, name: 'Nightmare Weapon' },
  { id: 799, name: 'Beguiling Haze' },
  { id: 800, name: 'Enduring Toxin' },
  { id: 801, name: 'Shroud of Silence' },
  { id: 802, name: 'Expose Defenses' },
  { id: 803, name: 'Power Leech' },
  { id: 804, name: 'Arcane Languor' },
  { id: 805, name: 'Animate Vampiric Horror' },
  { id: 806, name: "Cultist's Fervor" },
  { id: 808, name: "Reaper's Mark" },
  { id: 809, name: 'Shatterstone' },
  { id: 810, name: "Protector's Defense" },
  { id: 811, name: 'Run as One' },
  { id: 812, name: 'Defiant Was Xinrae' },
  { id: 813, name: "Lyssa's Aura" },
  { id: 814, name: 'Shadow Refuge' },
  { id: 815, name: 'Scorpion Wire' },
  { id: 816, name: 'Mirrored Stance' },
  { id: 817, name: 'Discord' },
  { id: 818, name: 'Well of Weariness' },
  { id: 819, name: 'Vampiric Spirit' },
  { id: 820, name: 'Depravity' },
  { id: 821, name: 'Icy Veins' },
  { id: 822, name: 'Weaken Knees' },
  { id: 823, name: 'Burning Speed' },
  { id: 824, name: 'Lava Arrows' },
  { id: 825, name: 'Bed of Coals' },
  { id: 826, name: 'Shadow Form' },
  { id: 827, name: 'Siphon Strength' },
  { id: 828, name: 'Vile Miasma' },
  { id: 830, name: 'Ray of Judgment' },
  { id: 831, name: 'Primal Rage' },
  { id: 832, name: 'Animate Flesh Golem' },
  { id: 834, name: 'Reckless Haste' },
  { id: 835, name: 'Blood Bond' },
  { id: 836, name: 'Ride the Lightning' },
  { id: 837, name: 'Energy Boon' },
  { id: 838, name: "Dwayna's Sorrow" },
  { id: 839, name: '&quot;Retreat!&quot;' },
  { id: 840, name: 'Poisoned Heart' },
  { id: 841, name: 'Fetid Ground' },
  { id: 842, name: 'Arc Lightning' },
  { id: 843, name: 'Gust' },
  { id: 844, name: 'Churning Earth' },
  { id: 845, name: 'Liquid Flame' },
  { id: 846, name: 'Steam' },
  { id: 847, name: 'Boon Signet' },
  { id: 848, name: 'Reverse Hex' },
  { id: 849, name: 'Lacerating Chop' },
  { id: 850, name: 'Fierce Blow' },
  { id: 851, name: 'Sun and Moon Slash' },
  { id: 852, name: 'Splinter Shot' },
  { id: 853, name: "Melandru's Shot" },
  { id: 854, name: 'Snare' },
  { id: 858, name: 'Dancing Daggers' },
  { id: 859, name: 'Conjure Nightmare' },
  { id: 860, name: 'Signet of Disruption' },
  { id: 862, name: 'Ravenous Gaze' },
  { id: 863, name: 'Order of Apostasy' },
  { id: 864, name: 'Oppressive Gaze' },
  { id: 865, name: 'Lightning Hammer' },
  { id: 866, name: 'Vapor Blade' },
  { id: 867, name: 'Healing Light' },
  { id: 869, name: '&quot;Coward!&quot;' },
  { id: 870, name: 'Pestilence' },
  { id: 871, name: 'Shadowsong' },
  { id: 876, name: 'Signet of Shadows' },
  { id: 877, name: "Lyssa's Balance" },
  { id: 878, name: 'Visions of Regret' },
  { id: 879, name: 'Illusion of Pain' },
  { id: 880, name: 'Stolen Speed' },
  { id: 881, name: 'Ether Signet' },
  { id: 882, name: 'Signet of Disenchantment' },
  { id: 883, name: 'Vocal Minority' },
  { id: 884, name: 'Searing Flames' },
  { id: 885, name: 'Shield Guardian' },
  { id: 886, name: 'Restful Breeze' },
  { id: 887, name: 'Signet of Rejuvenation' },
  { id: 888, name: 'Whirling Axe' },
  { id: 889, name: 'Forceful Blow' },
  { id: 891, name: '&quot;None Shall Pass!&quot;' },
  { id: 892, name: 'Quivering Blade' },
  { id: 893, name: 'Seeking Arrows' },
  { id: 898, name: 'Overload' },
  { id: 899, name: 'Images of Remorse' },
  { id: 900, name: 'Shared Burden' },
  { id: 901, name: 'Soul Bind' },
  { id: 902, name: 'Blood of the Aggressor' },
  { id: 903, name: 'Icy Prism' },
  { id: 904, name: 'Furious Axe' },
  { id: 905, name: 'Auspicious Blow' },
  { id: 906, name: '&quot;On Your Knees!&quot;' },
  { id: 907, name: 'Dragon Slash' },
  { id: 908, name: "Marauder's Shot" },
  { id: 909, name: 'Focused Shot' },
  { id: 910, name: 'Spirit Rift' },
  { id: 911, name: 'Union' },
  { id: 913, name: 'Tranquil Was Tanasen' },
  { id: 914, name: 'Consume Soul' },
  { id: 915, name: 'Spirit Light' },
  { id: 916, name: 'Lamentation' },
  { id: 917, name: 'Rupture Soul' },
  { id: 918, name: 'Spirit to Flesh' },
  { id: 919, name: 'Spirit Burn' },
  { id: 920, name: 'Destruction' },
  { id: 921, name: 'Dissonance' },
  { id: 923, name: 'Disenchantment' },
  { id: 925, name: 'Recall' },
  { id: 926, name: 'Sharpen Daggers' },
  { id: 927, name: 'Shameful Fear' },
  { id: 928, name: 'Shadow Shroud' },
  { id: 929, name: 'Shadow of Haste' },
  { id: 930, name: 'Auspicious Incantation' },
  { id: 931, name: 'Power Return' },
  { id: 932, name: 'Complicate' },
  { id: 933, name: 'Shatter Storm' },
  { id: 934, name: 'Unnatural Signet' },
  { id: 935, name: 'Rising Bile' },
  { id: 936, name: 'Envenom Enchantments' },
  { id: 937, name: 'Shockwave' },
  { id: 938, name: 'Ward of Stability' },
  { id: 939, name: 'Icy Shackles' },
  { id: 941, name: 'Blessed Light' },
  { id: 942, name: 'Withdraw Hexes' },
  { id: 943, name: 'Extinguish' },
  { id: 944, name: 'Signet of Strength' },
  { id: 946, name: "Trapper's Focus" },
  { id: 947, name: 'Brambles' },
  { id: 948, name: 'Desperate Strike' },
  { id: 949, name: 'Way of the Fox' },
  { id: 950, name: 'Shadowy Burden' },
  { id: 951, name: 'Siphon Speed' },
  { id: 952, name: "Death's Charge" },
  { id: 953, name: 'Power Flux' },
  { id: 954, name: 'Expel Hexes' },
  { id: 955, name: 'Rip Enchantment' },
  { id: 957, name: 'Spell Shield' },
  { id: 958, name: 'Healing Whisper' },
  { id: 959, name: 'Ethereal Light' },
  { id: 960, name: 'Release Enchantments' },
  { id: 961, name: 'Lacerate' },
  { id: 962, name: 'Spirit Transfer' },
  { id: 963, name: 'Restoration' },
  { id: 964, name: 'Vengeful Weapon' },
  { id: 973, name: 'Blinding Powder' },
  { id: 974, name: 'Mantis Touch' },
  { id: 975, name: 'Exhausting Assault' },
  { id: 976, name: 'Repeating Strike' },
  { id: 977, name: 'Way of the Lotus' },
  { id: 978, name: 'Mark of Instability' },
  { id: 979, name: 'Mistrust' },
  { id: 980, name: 'Feast of Souls' },
  { id: 981, name: 'Recuperation' },
  { id: 982, name: 'Shelter' },
  { id: 983, name: 'Weapon of Shadow' },
  { id: 985, name: 'Caltrops' },
  { id: 986, name: 'Nine Tail Strike' },
  { id: 987, name: 'Way of the Empty Palm' },
  { id: 988, name: 'Temple Strike' },
  { id: 989, name: 'Golden Phoenix Strike' },
  { id: 990, name: 'Expunge Enchantments' },
  { id: 991, name: 'Deny Hexes' },
  { id: 992, name: 'Triple Chop' },
  { id: 993, name: 'Enraged Smash' },
  { id: 994, name: 'Renewing Smash' },
  { id: 995, name: 'Tiger Stance' },
  { id: 996, name: 'Standing Slash' },
  { id: 997, name: 'Famine' },
  { id: 1014, name: "&quot;Let's Get 'Em!&quot;" },
  { id: 1018, name: 'Critical Eye' },
  { id: 1019, name: 'Critical Strike' },
  { id: 1020, name: 'Blades of Steel' },
  { id: 1021, name: 'Jungle Strike' },
  { id: 1022, name: 'Wild Strike' },
  { id: 1023, name: 'Leaping Mantis Sting' },
  { id: 1024, name: 'Black Mantis Thrust' },
  { id: 1025, name: 'Disrupting Stab' },
  { id: 1026, name: 'Golden Lotus Strike' },
  { id: 1027, name: 'Critical Defenses' },
  { id: 1028, name: 'Way of Perfection' },
  { id: 1029, name: 'Dark Apostasy' },
  { id: 1030, name: "Locust's Fury" },
  { id: 1031, name: 'Shroud of Distress' },
  { id: 1032, name: 'Heart of Shadow' },
  { id: 1033, name: 'Impale' },
  { id: 1034, name: 'Seeping Wound' },
  { id: 1035, name: "Assassin's Promise" },
  { id: 1036, name: 'Signet of Malice' },
  { id: 1037, name: 'Dark Escape' },
  { id: 1038, name: 'Crippling Dagger' },
  { id: 1040, name: 'Spirit Walk' },
  { id: 1041, name: 'Unseen Fury' },
  { id: 1042, name: 'Flashing Blades' },
  { id: 1043, name: 'Dash' },
  { id: 1044, name: 'Dark Prison' },
  { id: 1045, name: 'Palm Strike' },
  { id: 1048, name: 'Revealed Enchantment' },
  { id: 1049, name: 'Revealed Hex' },
  { id: 1052, name: 'Accumulated Pain' },
  { id: 1053, name: 'Psychic Distraction' },
  { id: 1054, name: "Ancestor's Visage" },
  { id: 1055, name: 'Recurring Insecurity' },
  { id: 1056, name: "Kitah's Burden" },
  { id: 1057, name: 'Psychic Instability' },
  { id: 1059, name: 'Hex Eater Signet' },
  { id: 1061, name: 'Feedback' },
  { id: 1062, name: 'Arcane Larceny' },
  { id: 1066, name: 'Spoil Victor' },
  { id: 1067, name: 'Lifebane Strike' },
  { id: 1068, name: 'Bitter Chill' },
  { id: 1069, name: 'Taste of Pain' },
  { id: 1070, name: 'Defile Enchantments' },
  { id: 1071, name: 'Shivers of Dread' },
  { id: 1075, name: 'Vampiric Swarm' },
  { id: 1076, name: 'Blood Drinker' },
  { id: 1077, name: 'Vampiric Bite' },
  { id: 1078, name: "Wallow's Bite" },
  { id: 1079, name: 'Enfeebling Touch' },
  { id: 1081, name: "Teinai's Wind" },
  { id: 1082, name: 'Shock Arrow' },
  { id: 1083, name: 'Unsteady Ground' },
  { id: 1084, name: 'Sliver Armor' },
  { id: 1085, name: 'Ash Blast' },
  { id: 1086, name: "Dragon's Stomp" },
  { id: 1088, name: 'Second Wind' },
  { id: 1090, name: 'Smoldering Embers' },
  { id: 1091, name: 'Double Dragon' },
  { id: 1093, name: "Teinai's Heat" },
  { id: 1094, name: 'Breath of Fire' },
  { id: 1095, name: 'Star Burst' },
  { id: 1096, name: 'Glyph of Essence' },
  { id: 1097, name: "Teinai's Prison" },
  { id: 1098, name: 'Mirror of Ice' },
  { id: 1099, name: "Teinai's Crystals" },
  { id: 1113, name: "Kirin's Wrath" },
  { id: 1114, name: 'Spirit Bond' },
  { id: 1115, name: 'Air of Enchantment' },
  { id: 1117, name: "Heaven's Delight" },
  { id: 1118, name: 'Healing Burst' },
  { id: 1119, name: "Karei's Healing Circle" },
  { id: 1120, name: "Jamei's Gaze" },
  { id: 1121, name: 'Gift of Health' },
  { id: 1123, name: 'Life Sheath' },
  { id: 1126, name: 'Empathic Removal' },
  { id: 1128, name: 'Resurrection Chant' },
  { id: 1129, name: 'Word of Censure' },
  { id: 1130, name: 'Spear of Light' },
  { id: 1131, name: 'Stonesoul Strike' },
  { id: 1133, name: 'Drunken Blow' },
  { id: 1134, name: "Leviathan's Sweep" },
  { id: 1135, name: 'Jaizhenju Strike' },
  { id: 1136, name: 'Penetrating Chop' },
  { id: 1137, name: 'Yeti Smash' },
  { id: 1140, name: 'Storm of Swords' },
  { id: 1141, name: '&quot;You Will Die!&quot;' },
  { id: 1142, name: 'Auspicious Parry' },
  { id: 1144, name: 'Silverwing Slash' },
  { id: 1146, name: 'Shove' },
  { id: 1191, name: 'Sundering Attack' },
  { id: 1192, name: "Zojun's Shot" },
  { id: 1194, name: 'Predatory Bond' },
  { id: 1195, name: 'Heal as One' },
  { id: 1196, name: "Zojun's Haste" },
  { id: 1197, name: 'Needling Shot' },
  { id: 1198, name: 'Broad Head Arrow' },
  { id: 1199, name: 'Glass Arrows' },
  { id: 1200, name: "Archer's Signet" },
  { id: 1201, name: 'Savage Pounce' },
  { id: 1202, name: 'Enraged Lunge' },
  { id: 1203, name: 'Bestial Mauling' },
  { id: 1205, name: 'Poisonous Bite' },
  { id: 1206, name: 'Pounce' },
  { id: 1209, name: 'Bestial Fury' },
  { id: 1211, name: "Viper's Nest" },
  { id: 1212, name: 'Equinox' },
  { id: 1213, name: 'Tranquility' },
  { id: 1215, name: 'Clamor of Souls' },
  { id: 1217, name: 'Ritual Lord' },
  { id: 1218, name: 'Cruel Was Daoshen' },
  { id: 1219, name: 'Protective Was Kaolai' },
  { id: 1220, name: 'Attuned Was Songkai' },
  { id: 1221, name: 'Resilient Was Xiko' },
  { id: 1222, name: 'Lively Was Naomei' },
  { id: 1223, name: 'Anguished Was Lingwah' },
  { id: 1224, name: 'Draw Spirit' },
  { id: 1225, name: 'Channeled Strike' },
  { id: 1226, name: 'Spirit Boon Strike' },
  { id: 1227, name: 'Essence Strike' },
  { id: 1228, name: 'Spirit Siphon' },
  { id: 1229, name: 'Explosive Growth' },
  { id: 1230, name: 'Boon of Creation' },
  { id: 1231, name: 'Spirit Channeling' },
  { id: 1232, name: 'Armor of Unfeeling' },
  { id: 1233, name: 'Soothing Memories' },
  { id: 1234, name: 'Mend Body and Soul' },
  { id: 1235, name: 'Dulled Weapon' },
  { id: 1236, name: 'Binding Chains' },
  { id: 1237, name: 'Painful Bond' },
  { id: 1238, name: 'Signet of Creation' },
  { id: 1239, name: 'Signet of Spirits' },
  { id: 1240, name: 'Soul Twisting' },
  { id: 1244, name: 'Ghostly Haste' },
  { id: 1245, name: 'Gaze from Beyond' },
  { id: 1246, name: "Ancestors' Rage" },
  { id: 1247, name: 'Pain' },
  { id: 1249, name: 'Displacement' },
  { id: 1250, name: 'Preservation' },
  { id: 1251, name: 'Life' },
  { id: 1252, name: 'Earthbind' },
  { id: 1253, name: 'Bloodsong' },
  { id: 1255, name: 'Wanderlust' },
  { id: 1257, name: 'Spirit Light Weapon' },
  { id: 1258, name: 'Brutal Weapon' },
  { id: 1259, name: 'Guided Weapon' },
  { id: 1260, name: 'Meekness' },
  { id: 1261, name: 'Frigid Armor' },
  { id: 1262, name: 'Healing Ring' },
  { id: 1263, name: 'Renew Life' },
  { id: 1264, name: 'Doom' },
  { id: 1265, name: "Wielder's Boon" },
  { id: 1266, name: 'Soothing' },
  { id: 1267, name: 'Vital Weapon' },
  { id: 1268, name: 'Weapon of Quickening' },
  { id: 1269, name: 'Signet of Rage' },
  { id: 1333, name: 'Extend Conditions' },
  { id: 1334, name: 'Hypochondria' },
  { id: 1335, name: "Wastrel's Demise" },
  { id: 1336, name: 'Spiritual Pain' },
  { id: 1337, name: 'Drain Delusions' },
  { id: 1338, name: 'Persistence of Memory' },
  { id: 1339, name: 'Symbols of Inspiration' },
  { id: 1340, name: 'Symbolic Celerity' },
  { id: 1341, name: 'Frustration' },
  { id: 1342, name: 'Tease' },
  { id: 1343, name: 'Ether Phantom' },
  { id: 1344, name: 'Web of Disruption' },
  { id: 1345, name: "Enchanter's Conundrum" },
  { id: 1346, name: 'Signet of Illusions' },
  { id: 1347, name: 'Discharge Enchantment' },
  { id: 1348, name: 'Hex Eater Vortex' },
  { id: 1349, name: 'Mirror of Disenchantment' },
  { id: 1350, name: 'Simple Thievery' },
  { id: 1351, name: 'Animate Shambling Horror' },
  { id: 1352, name: 'Order of Undeath' },
  { id: 1353, name: 'Putrid Flesh' },
  { id: 1354, name: 'Feast for the Dead' },
  { id: 1355, name: 'Jagged Bones' },
  { id: 1356, name: 'Contagion' },
  { id: 1358, name: 'Ulcerous Lungs' },
  { id: 1359, name: 'Pain of Disenchantment' },
  { id: 1360, name: 'Mark of Fury' },
  { id: 1362, name: 'Corrupt Enchantment' },
  { id: 1363, name: 'Signet of Sorrow' },
  { id: 1364, name: 'Signet of Suffering' },
  { id: 1365, name: 'Signet of Lost Souls' },
  { id: 1366, name: 'Well of Darkness' },
  { id: 1367, name: 'Blinding Surge' },
  { id: 1368, name: 'Chilling Winds' },
  { id: 1369, name: 'Lightning Bolt' },
  { id: 1370, name: "Storm Djinn's Haste" },
  { id: 1371, name: 'Stone Striker' },
  { id: 1372, name: 'Sandstorm' },
  { id: 1373, name: 'Stone Sheath' },
  { id: 1374, name: 'Ebon Hawk' },
  { id: 1375, name: 'Stoneflesh Aura' },
  { id: 1376, name: 'Glyph of Restoration' },
  { id: 1377, name: 'Ether Prism' },
  { id: 1378, name: 'Master of Magic' },
  { id: 1379, name: 'Glowing Gaze' },
  { id: 1380, name: 'Savannah Heat' },
  { id: 1381, name: "Flame Djinn's Haste" },
  { id: 1382, name: 'Freezing Gust' },
  { id: 1390, name: "Judge's Intervention" },
  { id: 1391, name: 'Supportive Spirit' },
  { id: 1392, name: 'Watchful Healing' },
  { id: 1393, name: "Healer's Boon" },
  { id: 1394, name: "Healer's Covenant" },
  { id: 1395, name: "Balthazar's Pendulum" },
  { id: 1396, name: 'Words of Comfort' },
  { id: 1397, name: 'Light of Deliverance' },
  { id: 1398, name: 'Scourge Enchantment' },
  { id: 1399, name: 'Shield of Absorption' },
  { id: 1400, name: 'Reversal of Damage' },
  { id: 1401, name: 'Mending Touch' },
  { id: 1402, name: 'Critical Chop' },
  { id: 1403, name: 'Agonizing Chop' },
  { id: 1404, name: 'Flail' },
  { id: 1405, name: 'Charging Strike' },
  { id: 1406, name: 'Headbutt' },
  { id: 1407, name: "Lion's Comfort" },
  { id: 1408, name: 'Rage of the Ntouka' },
  { id: 1409, name: 'Mokele Smash' },
  { id: 1410, name: 'Overbearing Smash' },
  { id: 1411, name: 'Signet of Stamina' },
  { id: 1412, name: "&quot;You're All Alone!&quot;" },
  { id: 1413, name: 'Burst of Aggression' },
  { id: 1414, name: 'Enraging Charge' },
  { id: 1415, name: 'Crippling Slash' },
  { id: 1416, name: 'Barbarous Slice' },
  { id: 1465, name: 'Prepared Shot' },
  { id: 1466, name: 'Burning Arrow' },
  { id: 1467, name: 'Arcing Shot' },
  { id: 1468, name: 'Strike as One' },
  { id: 1469, name: 'Crossfire' },
  { id: 1470, name: 'Barbed Arrows' },
  { id: 1471, name: "Scavenger's Focus" },
  { id: 1472, name: 'Toxicity' },
  { id: 1473, name: 'Quicksand' },
  { id: 1474, name: "Storm's Embrace" },
  { id: 1475, name: "Trapper's Speed" },
  { id: 1476, name: 'Tripwire' },
  { id: 1478, name: 'Renewing Surge' },
  { id: 1479, name: 'Offering of Spirit' },
  { id: 1480, name: "Spirit's Gift" },
  { id: 1481, name: 'Death Pact Signet' },
  { id: 1482, name: 'Reclaim Essence' },
  { id: 1483, name: 'Banishing Strike' },
  { id: 1484, name: 'Mystic Sweep' },
  { id: 1485, name: "Eremite's Attack" },
  { id: 1486, name: 'Reap Impurities' },
  { id: 1487, name: 'Twin Moon Sweep' },
  { id: 1488, name: 'Victorious Sweep' },
  { id: 1489, name: 'Irresistible Sweep' },
  { id: 1490, name: 'Pious Assault' },
  { id: 1491, name: 'Mystic Twister' },
  { id: 1493, name: "Grenth's Fingers" },
  { id: 1495, name: 'Aura of Thorns' },
  { id: 1496, name: "Balthazar's Rage" },
  { id: 1497, name: 'Dust Cloak' },
  { id: 1498, name: 'Staggering Force' },
  { id: 1499, name: 'Pious Renewal' },
  { id: 1500, name: 'Mirage Cloak' },
  { id: 1502, name: 'Arcane Zeal' },
  { id: 1503, name: 'Mystic Vigor' },
  { id: 1504, name: 'Watchful Intervention' },
  { id: 1505, name: 'Vow of Piety' },
  { id: 1506, name: 'Vital Boon' },
  { id: 1507, name: 'Heart of Holy Flame' },
  { id: 1508, name: 'Extend Enchantments' },
  { id: 1509, name: 'Faithful Intervention' },
  { id: 1510, name: 'Sand Shards' },
  { id: 1512, name: "Lyssa's Haste" },
  { id: 1513, name: 'Guiding Hands' },
  { id: 1514, name: 'Fleeting Stability' },
  { id: 1515, name: 'Armor of Sanctity' },
  { id: 1516, name: 'Mystic Regeneration' },
  { id: 1517, name: 'Vow of Silence' },
  { id: 1518, name: 'Avatar of Balthazar' },
  { id: 1519, name: 'Avatar of Dwayna' },
  { id: 1520, name: 'Avatar of Grenth' },
  { id: 1521, name: 'Avatar of Lyssa' },
  { id: 1522, name: 'Avatar of Melandru' },
  { id: 1523, name: 'Meditation' },
  { id: 1524, name: "Eremite's Zeal" },
  { id: 1525, name: 'Natural Healing' },
  { id: 1526, name: 'Imbue Health' },
  { id: 1527, name: 'Mystic Healing' },
  { id: 1528, name: "Dwayna's Touch" },
  { id: 1529, name: 'Pious Restoration' },
  { id: 1530, name: 'Signet of Pious Light' },
  { id: 1531, name: 'Intimidating Aura' },
  { id: 1532, name: 'Mystic Sandstorm' },
  { id: 1533, name: 'Winds of Disenchantment' },
  { id: 1534, name: 'Rending Touch' },
  { id: 1535, name: 'Crippling Sweep' },
  { id: 1536, name: 'Wounding Strike' },
  { id: 1537, name: 'Wearying Strike' },
  { id: 1538, name: "Lyssa's Assault" },
  { id: 1539, name: 'Chilling Victory' },
  { id: 1540, name: 'Conviction' },
  { id: 1541, name: 'Enchanted Haste' },
  { id: 1542, name: 'Pious Concentration' },
  { id: 1543, name: 'Pious Haste' },
  { id: 1544, name: 'Whirling Charge' },
  { id: 1545, name: 'Test of Faith' },
  { id: 1546, name: 'Blazing Spear' },
  { id: 1547, name: 'Mighty Throw' },
  { id: 1548, name: 'Cruel Spear' },
  { id: 1549, name: "Harrier's Toss" },
  { id: 1550, name: 'Unblockable Throw' },
  { id: 1551, name: 'Spear of Lightning' },
  { id: 1552, name: 'Wearying Spear' },
  { id: 1553, name: 'Anthem of Fury' },
  { id: 1554, name: 'Crippling Anthem' },
  { id: 1555, name: 'Defensive Anthem' },
  { id: 1556, name: 'Godspeed' },
  { id: 1557, name: 'Anthem of Flame' },
  { id: 1558, name: '&quot;Go for the Eyes!&quot;' },
  { id: 1559, name: 'Anthem of Envy' },
  { id: 1560, name: 'Song of Power' },
  { id: 1561, name: 'Zealous Anthem' },
  { id: 1562, name: 'Aria of Zeal' },
  { id: 1563, name: 'Lyric of Zeal' },
  { id: 1564, name: 'Ballad of Restoration' },
  { id: 1565, name: 'Chorus of Restoration' },
  { id: 1566, name: 'Aria of Restoration' },
  { id: 1567, name: 'Song of Concentration' },
  { id: 1568, name: 'Anthem of Guidance' },
  { id: 1569, name: 'Energizing Chorus' },
  { id: 1570, name: 'Song of Purification' },
  { id: 1571, name: 'Hexbreaker Aria' },
  { id: 1572, name: '&quot;Brace Yourself!&quot;' },
  { id: 1573, name: 'Awe' },
  { id: 1574, name: 'Enduring Harmony' },
  { id: 1575, name: 'Blazing Finale' },
  { id: 1576, name: 'Burning Refrain' },
  { id: 1577, name: 'Finale of Restoration' },
  { id: 1578, name: 'Mending Refrain' },
  { id: 1579, name: 'Purifying Finale' },
  { id: 1580, name: 'Bladeturn Refrain' },
  { id: 1581, name: 'Glowing Signet' },
  { id: 1583, name: "Leader's Zeal" },
  { id: 1584, name: "Leader's Comfort" },
  { id: 1585, name: 'Signet of Synergy' },
  { id: 1586, name: 'Angelic Protection' },
  { id: 1587, name: 'Angelic Bond' },
  { id: 1588, name: 'Cautery Signet' },
  { id: 1589, name: '&quot;Stand Your Ground!&quot;' },
  { id: 1590, name: '&quot;Lead the Way!&quot;' },
  { id: 1591, name: '&quot;Make Haste!&quot;' },
  { id: 1592, name: '&quot;We Shall Return!&quot;' },
  { id: 1593, name: '&quot;Never Give Up!&quot;' },
  { id: 1594, name: '&quot;Help Me!&quot;' },
  { id: 1595, name: '&quot;Fall Back!&quot;' },
  { id: 1596, name: '&quot;Incoming!&quot;' },
  { id: 1597, name: "&quot;They're on Fire!&quot;" },
  { id: 1598, name: '&quot;Never Surrender!&quot;' },
  { id: 1599, name: "&quot;It's Just a Flesh Wound.&quot;" },
  { id: 1600, name: 'Barbed Spear' },
  { id: 1601, name: 'Vicious Attack' },
  { id: 1602, name: 'Stunning Strike' },
  { id: 1603, name: 'Merciless Spear' },
  { id: 1604, name: 'Disrupting Throw' },
  { id: 1605, name: 'Wild Throw' },
  { id: 1633, name: 'Malicious Strike' },
  { id: 1634, name: 'Shattering Assault' },
  { id: 1635, name: 'Golden Skull Strike' },
  { id: 1636, name: 'Black Spider Strike' },
  { id: 1637, name: 'Golden Fox Strike' },
  { id: 1638, name: 'Deadly Haste' },
  { id: 1639, name: "Assassin's Remedy" },
  { id: 1640, name: "Fox's Promise" },
  { id: 1641, name: 'Feigned Neutrality' },
  { id: 1642, name: 'Hidden Caltrops' },
  { id: 1643, name: 'Assault Enchantments' },
  { id: 1644, name: "Wastrel's Collapse" },
  { id: 1645, name: 'Lift Enchantment' },
  { id: 1646, name: 'Augury of Death' },
  { id: 1647, name: 'Signet of Toxic Shock' },
  { id: 1648, name: 'Signet of Twilight' },
  { id: 1649, name: 'Way of the Assassin' },
  { id: 1650, name: 'Shadow Walk' },
  { id: 1651, name: "Death's Retreat" },
  { id: 1652, name: 'Shadow Prison' },
  { id: 1653, name: 'Swap' },
  { id: 1654, name: 'Shadow Meld' },
  { id: 1655, name: 'Price of Pride' },
  { id: 1656, name: 'Air of Disenchantment' },
  { id: 1657, name: 'Signet of Clumsiness' },
  { id: 1658, name: 'Symbolic Posture' },
  { id: 1659, name: 'Toxic Chill' },
  { id: 1660, name: 'Well of Silence' },
  { id: 1661, name: 'Glowstone' },
  { id: 1662, name: 'Mind Blast' },
  { id: 1663, name: 'Elemental Flame' },
  { id: 1664, name: 'Invoke Lightning' },
  { id: 1683, name: 'Pensive Guardian' },
  { id: 1684, name: "Scribe's Insight" },
  { id: 1685, name: 'Holy Haste' },
  { id: 1686, name: 'Glimmer of Light' },
  { id: 1687, name: 'Zealous Benediction' },
  { id: 1688, name: "Defender's Zeal" },
  { id: 1689, name: 'Signet of Mystic Wrath' },
  { id: 1690, name: 'Signet of Removal' },
  { id: 1691, name: 'Dismiss Condition' },
  { id: 1692, name: 'Divert Hexes' },
  { id: 1693, name: 'Counterattack' },
  { id: 1694, name: 'Magehunter Strike' },
  { id: 1695, name: "Soldier's Strike" },
  { id: 1696, name: 'Decapitate' },
  { id: 1697, name: "Magehunter's Smash" },
  { id: 1698, name: "Soldier's Stance" },
  { id: 1699, name: "Soldier's Defense" },
  { id: 1700, name: 'Frenzied Defense' },
  { id: 1701, name: 'Steady Stance' },
  { id: 1702, name: 'Steelfang Slash' },
  { id: 1719, name: 'Screaming Shot' },
  { id: 1720, name: 'Keen Arrow' },
  { id: 1721, name: 'Rampage as One' },
  { id: 1722, name: 'Forked Arrow' },
  { id: 1723, name: 'Disrupting Accuracy' },
  { id: 1724, name: "Expert's Dexterity" },
  { id: 1725, name: 'Roaring Winds' },
  { id: 1726, name: 'Magebane Shot' },
  { id: 1727, name: 'Natural Stride' },
  { id: 1728, name: "Heket's Rampage" },
  { id: 1729, name: 'Smoke Trap' },
  { id: 1730, name: 'Infuriating Heat' },
  { id: 1731, name: 'Vocal Was Sogolon' },
  { id: 1732, name: 'Destructive Was Glaive' },
  { id: 1733, name: "Wielder's Strike" },
  { id: 1734, name: 'Gaze of Fury' },
  { id: 1736, name: "Spirit's Strength" },
  { id: 1737, name: "Wielder's Zeal" },
  { id: 1738, name: 'Sight Beyond Sight' },
  { id: 1739, name: 'Renewing Memories' },
  { id: 1740, name: "Wielder's Remedy" },
  { id: 1741, name: 'Ghostmirror Light' },
  { id: 1742, name: 'Signet of Ghostly Might' },
  { id: 1743, name: 'Signet of Binding' },
  { id: 1744, name: "Caretaker's Charge" },
  { id: 1745, name: 'Anguish' },
  { id: 1747, name: 'Empowerment' },
  { id: 1748, name: 'Recovery' },
  { id: 1749, name: 'Weapon of Fury' },
  { id: 1750, name: "Xinrae's Weapon" },
  { id: 1751, name: "Warmonger's Weapon" },
  { id: 1752, name: 'Weapon of Remedy' },
  { id: 1753, name: 'Rending Sweep' },
  { id: 1754, name: 'Onslaught' },
  { id: 1755, name: 'Mystic Corruption' },
  { id: 1756, name: "Grenth's Grasp" },
  { id: 1757, name: 'Veil of Thorns' },
  { id: 1758, name: "Harrier's Grasp" },
  { id: 1759, name: 'Vow of Strength' },
  { id: 1760, name: 'Ebon Dust Aura' },
  { id: 1761, name: 'Zealous Vow' },
  { id: 1762, name: 'Heart of Fury' },
  { id: 1763, name: 'Zealous Renewal' },
  { id: 1764, name: "Attacker's Insight" },
  { id: 1765, name: 'Rending Aura' },
  { id: 1766, name: 'Featherfoot Grace' },
  { id: 1767, name: "Reaper's Sweep" },
  { id: 1768, name: "Harrier's Haste" },
  { id: 1769, name: 'Focused Anger' },
  { id: 1770, name: 'Natural Temper' },
  { id: 1771, name: 'Song of Restoration' },
  { id: 1772, name: 'Lyric of Purification' },
  { id: 1773, name: "Soldier's Fury" },
  { id: 1774, name: 'Aggressive Refrain' },
  { id: 1775, name: 'Energizing Finale' },
  { id: 1776, name: 'Signet of Aggression' },
  { id: 1777, name: 'Remedy Signet' },
  { id: 1778, name: 'Signet of Return' },
  { id: 1779, name: '&quot;Make Your Time!&quot;' },
  { id: 1780, name: "&quot;Can't Touch This!&quot;" },
  { id: 1781, name: '&quot;Find Their Weakness!&quot;' },
  { id: 1782, name: '&quot;The Power Is Yours!&quot;' },
  { id: 1783, name: "Slayer's Spear" },
  { id: 1784, name: 'Swift Javelin' },
  { id: 1814, name: "Lightbringer's Gaze" },
  { id: 1815, name: 'Lightbringer Signet' },
  { id: 1816, name: 'Sunspear Rebirth Signet' },
  { id: 1986, name: 'Vampiric Assault' },
  { id: 1987, name: 'Lotus Strike' },
  { id: 1988, name: 'Golden Fang Strike' },
  { id: 1990, name: 'Falling Lotus Strike' },
  { id: 1991, name: "Sadist's Signet" },
  { id: 1992, name: 'Signet of Distraction' },
  { id: 1993, name: 'Signet of Recall' },
  { id: 1994, name: 'Power Lock' },
  { id: 1995, name: 'Waste Not, Want Not' },
  { id: 1996, name: 'Sum of All Fears' },
  { id: 1997, name: 'Withering Aura' },
  { id: 1998, name: 'Cacophony' },
  { id: 1999, name: "Winter's Embrace" },
  { id: 2000, name: 'Earthen Shackles' },
  { id: 2001, name: 'Ward of Weakness' },
  { id: 2002, name: 'Glyph of Swiftness' },
  { id: 2003, name: 'Cure Hex' },
  { id: 2004, name: 'Smite Condition' },
  { id: 2005, name: "Smiter's Boon" },
  { id: 2006, name: 'Castigation Signet' },
  { id: 2007, name: 'Purifying Veil' },
  { id: 2008, name: 'Pulverizing Smash' },
  { id: 2009, name: 'Keen Chop' },
  { id: 2010, name: 'Knee Cutter' },
  { id: 2011, name: 'Grapple' },
  { id: 2012, name: 'Radiant Scythe' },
  { id: 2013, name: "Grenth's Aura" },
  { id: 2014, name: 'Signet of Pious Restraint' },
  { id: 2015, name: "Farmer's Scythe" },
  { id: 2016, name: 'Energetic Was Lee Sa' },
  { id: 2017, name: 'Anthem of Weariness' },
  { id: 2018, name: 'Anthem of Disruption' },
  { id: 2052, name: 'Shadow Fang' },
  { id: 2053, name: 'Calculated Risk' },
  { id: 2054, name: 'Shrinking Armor' },
  { id: 2055, name: 'Aneurysm' },
  { id: 2056, name: 'Wandering Eye' },
  { id: 2057, name: 'Foul Feast' },
  { id: 2058, name: 'Putrid Bile' },
  { id: 2059, name: 'Shell Shock' },
  { id: 2060, name: 'Glyph of Immolation' },
  { id: 2061, name: 'Patient Spirit' },
  { id: 2062, name: 'Healing Ribbon' },
  { id: 2063, name: 'Aura of Stability' },
  { id: 2064, name: 'Spotless Mind' },
  { id: 2065, name: 'Spotless Soul' },
  { id: 2066, name: 'Disarm' },
  { id: 2067, name: '&quot;I Meant to Do That!&quot;' },
  { id: 2068, name: 'Rapid Fire' },
  { id: 2069, name: "Sloth Hunter's Shot" },
  { id: 2070, name: 'Aura Slicer' },
  { id: 2071, name: 'Zealous Sweep' },
  { id: 2072, name: 'Pure Was Li Ming' },
  { id: 2073, name: 'Weapon of Aggression' },
  { id: 2074, name: 'Chest Thumper' },
  { id: 2075, name: 'Hasty Refrain' },
  { id: 2101, name: 'Critical Agility' },
  { id: 2102, name: 'Cry of Pain' },
  { id: 2103, name: 'Necrosis' },
  { id: 2104, name: 'Intensity' },
  { id: 2105, name: 'Seed of Life' },
  { id: 2107, name: 'Whirlwind Attack' },
  { id: 2108, name: 'Never Rampage Alone' },
  { id: 2109, name: 'Eternal Aura' },
  { id: 2110, name: 'Vampirism' },
  { id: 2112, name: "&quot;There's Nothing to Fear!&quot;" },
  { id: 2116, name: 'Sneak Attack' },
  { id: 2135, name: 'Trampling Ox' },
  { id: 2136, name: 'Smoke Powder Defense' },
  { id: 2137, name: 'Confusing Images' },
  { id: 2138, name: "Hexer's Vigor" },
  { id: 2139, name: 'Masochism' },
  { id: 2140, name: 'Piercing Trap' },
  { id: 2141, name: 'Companionship' },
  { id: 2142, name: 'Feral Aggression' },
  { id: 2143, name: 'Disrupting Shot' },
  { id: 2144, name: 'Volley' },
  { id: 2145, name: 'Expert Focus' },
  { id: 2146, name: 'Pious Fury' },
  { id: 2147, name: 'Crippling Victory' },
  { id: 2148, name: 'Sundering Weapon' },
  { id: 2149, name: 'Weapon of Renewal' },
  { id: 2150, name: 'Maiming Spear' },
  { id: 2186, name: 'Signet of Deadly Corruption' },
  { id: 2187, name: 'Way of the Master' },
  { id: 2188, name: 'Defile Defenses' },
  { id: 2189, name: "Angorodon's Gaze" },
  { id: 2190, name: 'Magnetic Surge' },
  { id: 2191, name: 'Slippery Ground' },
  { id: 2192, name: 'Glowing Ice' },
  { id: 2193, name: 'Energy Blast' },
  { id: 2194, name: 'Distracting Strike' },
  { id: 2195, name: 'Symbolic Strike' },
  { id: 2196, name: "Soldier's Speed" },
  { id: 2197, name: 'Body Blow' },
  { id: 2198, name: 'Body Shot' },
  { id: 2199, name: 'Poison Tip Signet' },
  { id: 2200, name: 'Signet of Mystic Speed' },
  { id: 2201, name: 'Shield of Force' },
  { id: 2202, name: 'Mending Grip' },
  { id: 2203, name: 'Spiritleech Aura' },
  { id: 2204, name: 'Rejuvenation' },
  { id: 2205, name: 'Agony' },
  { id: 2206, name: 'Ghostly Weapon' },
  { id: 2207, name: 'Inspirational Speech' },
  { id: 2208, name: 'Burning Shield' },
  { id: 2209, name: 'Holy Spear' },
  { id: 2210, name: 'Spear Swipe' },
  { id: 2211, name: "Alkar's Alchemical Acid" },
  { id: 2212, name: 'Light of Deldrimor' },
  { id: 2213, name: 'Ear Bite' },
  { id: 2214, name: 'Low Blow' },
  { id: 2215, name: 'Brawling Headbutt' },
  { id: 2216, name: "&quot;Don't Trip!&quot;" },
  { id: 2217, name: "&quot;By Ural's Hammer!&quot;" },
  { id: 2218, name: 'Drunken Master' },
  { id: 2219, name: 'Great Dwarf Weapon' },
  { id: 2220, name: 'Great Dwarf Armor' },
  { id: 2221, name: 'Breath of the Great Dwarf' },
  { id: 2222, name: 'Snow Storm' },
  { id: 2223, name: 'Black Powder Mine' },
  { id: 2224, name: 'Summon Mursaat' },
  { id: 2225, name: 'Summon Ruby Djinn' },
  { id: 2226, name: 'Summon Ice Imp' },
  { id: 2227, name: 'Summon Naga Shaman' },
  { id: 2228, name: 'Deft Strike' },
  { id: 2229, name: 'Signet of Infection' },
  { id: 2230, name: 'Tryptophan Signet' },
  { id: 2231, name: 'Ebon Battle Standard of Courage' },
  { id: 2232, name: 'Ebon Battle Standard of Wisdom' },
  { id: 2233, name: 'Ebon Battle Standard of Honor' },
  { id: 2234, name: 'Ebon Vanguard Sniper Support' },
  { id: 2235, name: 'Ebon Vanguard Assassin Support' },
  { id: 2236, name: 'Well of Ruin' },
  { id: 2237, name: 'Atrophy' },
  { id: 2238, name: 'Spear of Redemption' },
  { id: 2353, name: '&quot;Finish Him!&quot;' },
  { id: 2354, name: '&quot;Dodge This!&quot;' },
  { id: 2355, name: '&quot;I Am the Strongest!&quot;' },
  { id: 2356, name: '&quot;I Am Unstoppable!&quot;' },
  { id: 2357, name: 'A Touch of Guile' },
  { id: 2358, name: '&quot;You Move Like a Dwarf!&quot;' },
  { id: 2359, name: '&quot;You Are All Weaklings!&quot;' },
  { id: 2360, name: 'Feel No Pain' },
  { id: 2361, name: 'Club of a Thousand Bears' },
  { id: 2374, name: 'Ursan Blessing' },
  { id: 2379, name: 'Volfen Blessing' },
  { id: 2384, name: 'Raven Blessing' },
  { id: 2411, name: 'Mindbender' },
  { id: 2412, name: 'Smooth Criminal' },
  { id: 2413, name: 'Technobabble' },
  { id: 2414, name: 'Radiation Field' },
  { id: 2415, name: 'Asuran Scan' },
  { id: 2416, name: 'Air of Superiority' },
  { id: 2417, name: 'Mental Block' },
  { id: 2418, name: 'Pain Inverter' },
  { id: 2420, name: 'Ebon Escape' },
  { id: 2421, name: 'Weakness Trap' },
  { id: 2422, name: 'Winds' },
  { id: 2423, name: 'Dwarven Stability' },
  { id: 2657, name: 'Call of Haste (PvP)' },
  { id: 2683, name: "Castigation Signet (Saul D'Alessio)" },
  { id: 2684, name: "Unnatural Signet (Saul D'Alessio)" },
  { id: 2734, name: 'Mind Wrack (PvP)' },
  { id: 2803, name: 'Mind Freeze (PvP)' },
  { id: 2804, name: 'Mind Shock (PvP)' },
  { id: 2805, name: 'Mist Form (PvP)' },
  { id: 2806, name: 'Ward Against Harm (PvP)' },
  { id: 2807, name: 'Ride the Lightning (PvP)' },
  { id: 2808, name: 'Enraged Smash (PvP)' },
  { id: 2809, name: 'Obsidian Flame (PvP)' },
  { id: 2857, name: 'Aegis (PvP)' },
  { id: 2858, name: '&quot;Watch Yourself!&quot; (PvP)' },
  { id: 2859, name: 'Enfeeble (PvP)' },
  { id: 2860, name: 'Ether Renewal (PvP)' },
  { id: 2861, name: 'Penetrating Attack (PvP)' },
  { id: 2862, name: 'Shadow Form (PvP)' },
  { id: 2863, name: 'Discord (PvP)' },
  { id: 2864, name: 'Sundering Attack (PvP)' },
  { id: 2866, name: 'Flesh of My Flesh (PvP)' },
  { id: 2867, name: "Ancestors' Rage (PvP)" },
  { id: 2868, name: 'Splinter Weapon (PvP)' },
  { id: 2869, name: "Assassin's Remedy (PvP)" },
  { id: 2871, name: 'Light of Deliverance (PvP)' },
  { id: 2872, name: 'Death Pact Signet (PvP)' },
  { id: 2875, name: "Harrier's Toss (PvP)" },
  { id: 2876, name: 'Defensive Anthem (PvP)' },
  { id: 2877, name: 'Ballad of Restoration (PvP)' },
  { id: 2878, name: 'Song of Restoration (PvP)' },
  { id: 2879, name: '&quot;Incoming!&quot; (PvP)' },
  { id: 2880, name: '&quot;Never Surrender!&quot; (PvP)' },
  { id: 2883, name: '&quot;For Great Justice!&quot; (PvP)' },
  { id: 2884, name: 'Mystic Regeneration (PvP)' },
  { id: 2885, name: 'Enfeebling Blood (PvP)' },
  { id: 2887, name: 'Signet of Judgment (PvP)' },
  { id: 2891, name: 'Unyielding Aura (PvP)' },
  { id: 2892, name: 'Spirit Bond (PvP)' },
  { id: 2893, name: 'Weapon of Warding (PvP)' },
  { id: 2895, name: "Smiter's Boon (PvP)" },
  { id: 2925, name: "Sloth Hunter's Shot (PvP)" },
  { id: 2959, name: "Expert's Dexterity (PvP)" },
  { id: 2965, name: 'Signet of Spirits (PvP)' },
  { id: 2966, name: 'Signet of Ghostly Might (PvP)' },
  { id: 2969, name: 'Read the Wind (PvP)' },
  { id: 2998, name: 'Fragility (PvP)' },
  { id: 2999, name: 'Strength of Honor (PvP)' },
  { id: 3002, name: "Warrior's Endurance (PvP)" },
  { id: 3003, name: 'Armor of Unfeeling (PvP)' },
  { id: 3005, name: 'Union (PvP)' },
  { id: 3006, name: 'Shadowsong (PvP)' },
  { id: 3007, name: 'Pain (PvP)' },
  { id: 3008, name: 'Destruction (PvP)' },
  { id: 3009, name: 'Soothing (PvP)' },
  { id: 3010, name: 'Displacement (PvP)' },
  { id: 3011, name: 'Preservation (PvP)' },
  { id: 3012, name: 'Life (PvP)' },
  { id: 3013, name: 'Recuperation (PvP)' },
  { id: 3014, name: 'Dissonance (PvP)' },
  { id: 3015, name: 'Earthbind (PvP)' },
  { id: 3016, name: 'Shelter (PvP)' },
  { id: 3017, name: 'Disenchantment (PvP)' },
  { id: 3018, name: 'Restoration (PvP)' },
  { id: 3019, name: 'Bloodsong (PvP)' },
  { id: 3020, name: 'Wanderlust (PvP)' },
  { id: 3021, name: 'Savannah Heat (PvP)' },
  { id: 3022, name: 'Gaze of Fury (PvP)' },
  { id: 3023, name: 'Anguish (PvP)' },
  { id: 3024, name: 'Empowerment (PvP)' },
  { id: 3025, name: 'Recovery (PvP)' },
  { id: 3026, name: '&quot;Go for the Eyes!&quot; (PvP)' },
  { id: 3027, name: '&quot;Brace Yourself!&quot; (PvP)' },
  { id: 3028, name: 'Blazing Finale (PvP)' },
  { id: 3029, name: 'Bladeturn Refrain (PvP)' },
  { id: 3030, name: 'Signet of Return (PvP)' },
  { id: 3031, name: "&quot;Can't Touch This!&quot; (PvP)" },
  { id: 3032, name: '&quot;Stand Your Ground!&quot; (PvP)' },
  { id: 3033, name: '&quot;We Shall Return!&quot; (PvP)' },
  { id: 3034, name: '&quot;Find Their Weakness!&quot; (PvP)' },
  { id: 3035, name: '&quot;Never Give Up!&quot; (PvP)' },
  { id: 3036, name: '&quot;Help Me!&quot; (PvP)' },
  { id: 3037, name: '&quot;Fall Back!&quot; (PvP)' },
  { id: 3038, name: 'Agony (PvP)' },
  { id: 3039, name: 'Rejuvenation (PvP)' },
  { id: 3040, name: 'Anthem of Disruption (PvP)' },
  { id: 3045, name: 'Comfort Animal (PvP)' },
  { id: 3047, name: "Melandru's Assault (PvP)" },
  { id: 3048, name: 'Shroud of Distress (PvP)' },
  { id: 3049, name: 'Unseen Fury (PvP)' },
  { id: 3050, name: 'Predatory Bond (PvP)' },
  { id: 3051, name: 'Enraged Lunge (PvP)' },
  { id: 3053, name: 'Signet of Deadly Corruption (PvP)' },
  { id: 3054, name: 'Masochism (PvP)' },
  { id: 3058, name: 'Unholy Feast (PvP)' },
  { id: 3059, name: 'Signet of Agony (PvP)' },
  { id: 3060, name: 'Escape (PvP)' },
  { id: 3061, name: 'Death Blossom (PvP)' },
  { id: 3062, name: 'Finale of Restoration (PvP)' },
  { id: 3063, name: 'Mantra of Resolve (PvP)' },
  { id: 3068, name: 'Charm Animal (Codex)' },
  { id: 3141, name: 'Lightning Reflexes (PvP)' },
  { id: 3143, name: 'Renewing Smash (PvP)' },
  { id: 3144, name: 'Heal as One (PvP)' },
  { id: 3145, name: 'Glass Arrows (PvP)' },
  { id: 3147, name: 'Keen Arrow (PvP)' },
  { id: 3148, name: 'Anthem of Envy (PvP)' },
  { id: 3149, name: 'Mending Refrain (PvP)' },
  { id: 3151, name: 'Empathy (PvP)' },
  { id: 3152, name: 'Crippling Anguish (PvP)' },
  { id: 3156, name: "Soldier's Stance (PvP)" },
  { id: 3157, name: 'Destructive Was Glaive (PvP)' },
  { id: 3179, name: 'Mantra of Signets (PvP)' },
  { id: 3180, name: 'Shatter Delusions (PvP)' },
  { id: 3181, name: 'Illusionary Weaponry (PvP)' },
  { id: 3183, name: 'Migraine (PvP)' },
  { id: 3184, name: 'Accumulated Pain (PvP)' },
  { id: 3185, name: 'Psychic Instability (PvP)' },
  { id: 3186, name: 'Shared Burden (PvP)' },
  { id: 3187, name: 'Stolen Speed (PvP)' },
  { id: 3188, name: 'Unnatural Signet (PvP)' },
  { id: 3189, name: 'Spiritual Pain (PvP)' },
  { id: 3190, name: 'Frustration (PvP)' },
  { id: 3191, name: 'Mistrust (PvP)' },
  { id: 3192, name: "Enchanter's Conundrum (PvP)" },
  { id: 3193, name: 'Signet of Clumsiness (PvP)' },
  { id: 3194, name: 'Mirror of Disenchantment (PvP)' },
  { id: 3195, name: 'Wandering Eye (PvP)' },
  { id: 3196, name: 'Calculated Risk (PvP)' },
  { id: 3204, name: 'Defy Pain (PvP)' },
  { id: 3232, name: 'Heal Party (PvP)' },
  { id: 3233, name: 'Spoil Victor (PvP)' },
  { id: 3234, name: 'Visions of Regret (PvP)' },
  { id: 3251, name: 'Fox Fangs (PvP)' },
  { id: 3252, name: 'Wild Strike (PvP)' },
  { id: 3263, name: 'Banishing Strike (PvP)' },
  { id: 3264, name: 'Twin Moon Sweep (PvP)' },
  { id: 3265, name: 'Irresistible Sweep (PvP)' },
  { id: 3266, name: 'Pious Assault (PvP)' },
  { id: 3269, name: 'Guiding Hands (PvP)' },
  { id: 3270, name: 'Avatar of Dwayna (PvP)' },
  { id: 3271, name: 'Avatar of Melandru (PvP)' },
  { id: 3272, name: 'Mystic Healing (PvP)' },
  { id: 3273, name: 'Signet of Pious Restraint (PvP)' },
  { id: 3289, name: 'Fevered Dreams (PvP)' },
  { id: 3346, name: 'Aura of Thorns (PvP)' },
  { id: 3347, name: 'Dust Cloak (PvP)' },
  { id: 3348, name: "Lyssa's Haste (PvP)" },
  { id: 3365, name: 'Onslaught (PvP)' },
  { id: 3366, name: 'Heart of Fury (PvP)' },
  { id: 3367, name: 'Wounding Strike (PvP)' },
  { id: 3368, name: 'Pious Fury (PvP)' },
  { id: 3373, name: 'Illusion of Haste (PvP)' },
  { id: 3374, name: 'Illusion of Pain (PvP)' },
  { id: 3375, name: 'Aura of Restoration (PvP)' },
  { id: 3386, name: 'Web of Disruption (PvP)' },
  { id: 3396, name: 'Lightning Hammer (PvP)' },
  { id: 3397, name: 'Elemental Flame (PvP)' },
  { id: 3398, name: 'Slippery Ground (PvP)' },
  { id: 3422, name: 'Time Ward' },
  { id: 3423, name: 'Soul Taker' },
  { id: 3424, name: 'Over the Limit' },
  { id: 3425, name: 'Judgment Strike' },
  { id: 3426, name: 'Seven Weapons Stance' },
  { id: 3427, name: '&quot;Together as One!&quot;' },
  { id: 3428, name: 'Shadow Theft' },
  { id: 3429, name: 'Weapons of Three Forges' },
  { id: 3430, name: 'Vow of Revolution' },
  { id: 3431, name: 'Heroic Refrain' },
]
